name: 'Software CICD'

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: buzzure-prod
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    name: 'Build and Deploy App'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
        working-directory: ./
      # deploy web app using Azure credentials
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      # Azure logout
      - name: logout
        run: |
          az logout
